### ISSUE TITLE
Scrape Data from Antitrust page https://www.competitionpolicyinternational.com/?s=Google

### ISSUE THREAD

**Issue by adellegia** [adellegia/antitRust#1]
- [x] Scrape articles for 5 platforms
- [x] Merge 
- [x] Extract fines
- [x] Extract countries
- [x] Remove unavailable articles 
- [x] Optional: Remove articles when no mention of 5 platforms

**Comment by janinepdevera** [comment]
Total number of articles: 7611

**Comment by adellegia** [comment]
- [x] Drop duplicate articles
- [x] Tag to a GAFAM company based on headline

Example:


![Image](https://user-images.githubusercontent.com/12932750/204112157-8b022e69-962f-4966-b9fe-19402edc7b89.png)

**Comment by adellegia** [comment]
See branch: scraping
- [x] Remove non-English articles before tokenizing

No. of English articles: 6885

For example, in STM, one topic is for Spanish articles:


![Image](https://user-images.githubusercontent.com/12932750/204112258-79263c7c-b573-44e4-b4fc-c6ed744e64de.png)

**Comment by adellegia** [comment]
After removing duplicates and non-English articles,
Total number of articles: 4256
